USE gamedb;

INSERT INTO story (storyId, body, createdAt, updatedAt) VALUES 
(1, 'As a knight serving in Princess Kaguya\'s personal guard, you\'ve been on shift since midday, and are going off shift with your partner when Princess Kaguya summons you alone into her receiving chambers. The room is small but warm, the walls decorated with tapestries depicting the heroes of the Moon Kingdom over the last few centuries. Princess Kaguya stands before a tapestry with a dragon serpentining through the skies over a stormy sea, claws outstretched and holding a shining pearl.\n
She turns when you salute from the doorway, her eyes taking you in. Her lips are pressed in a thin line, her shoulders taunt.\n
"Your mission, should you accept it, is to save Us."', now(), now()),
(2, '"This knight is at your command. Princess, what\'s happened?"\n
She smiles without it reaching her eyes, raising the fan in her hand. With it opening to cover her lower mouth, she glances to the side.\n
"I may sound dramatic, but truly, this is of great importance. The New Year Moon Ceremony is held tomorrow, yet the Pearl of the Seas has gone missing. We must have it back before the ceremony commences."\n
 A theft on this magnitude seems impossible, but if the Princess says it\'s the case, there\'s no room for you to doubt it now.', now(), now()),
(3, '"Command me at your will, Princess," you say without hesitation. She blinks as if startled, then laughs lightly behind a raised hand.\n
"So fast to agree! I see you\'re one of my most loyal knights indeed. In that case, here." Her hand falls to her side, and she pulls a slip of parchment out of her sleeve, extending it to you. When you accept it, she steps back. "Some individual seeking to disrupt tomorrow\'s ceremony has stolen the Pearl of the Seas. This is the response to the note they left in its place. Please deliver it to the Star Viewing Tower on the far side of the forest, next to the Sea of Tears."', now(), now()),
(4, 'You stare blankly, still thinking about how much you\'d like to eat and go to bed after your long shift. You remember yourself and blink and salute the Princess, but she\'s already noticed your blank stare, and is hiding her laughing mouth behind an upraised hand.\n
"Princess, this guard apologises. What would you have me do?"\n
"Sleep if I were kinder, but as it stands, I have a more pressing need for your services than allowing you to rest." Her hand lowers to her navel, and she fixes you with her gaze. "The Pearl of the Seas has been stolen. I need you to retrieve it."', now(), now()),
(5, 'Princess Kaguya turns, looking to the tapestry at her back. You realise the pearl in the dragon\'s claws is the Pearl of the Seas in question. No wonder she\'d been standing here in contemplation when you arrived.\n
"The Pearl of the Seas is required for the Dragon Dance to give thanks for the year that\'s ending, and to welcome good luck and prosperity in the year to come. Without it, the ceremony won\'t be considered auspicious, and the people\'s hearts will be uneasy."\n
As one of the people in question, you understand what she means. Still, this doesn\'t answer where it\'s gone, or what the Princess expects you to do.\n
"Then does the Princess know where the Pearl of the Seas has been taken?"\n
She turns to regard you from over her shoulder, then makes a noncommittal noise, pulling a narrow, rolled scroll out of her sleeve. "Yes. Please deliver this to the Star Viewing Tower on the other side of the forest, next to sea, and retrieve the Pearl of the Seas from the one you find there."', now(), now()),
(6, '"Please deliver a scroll to the Star Viewing Tower on the other side of the forest, next to Mare Imbrium. Once you do, the one who took the Pearl should place it in your care."\n
Such a mysterious and self assured statement, but that\'s the way with royalty. The Princess honours you with a tired smile, reaching into her sleeve and withdrawing a narrow, rolled scroll. She holds it out to you, waiting for you to accept it. Once you do, she says, "May you journey on swift feet, with fair winds at your back and the stars to guide you."\n
So dismissed, you salute and exit the room to prepare for your secretive journey.', now(), now()),
(7, 'The forest is rich with sound at this hour of the night, insects sending out their small calls while unseen paws patter across leaves made invisible in the dark. Crystal tree branches catch the starlight, reflecting it back in quiet patterns that are soothing to your practiced eyes. You considered taking one of the mounts available to you as a knight, but the stables are a highly visible place, and so you decided to proceed on foot.\n
You\'re familiar with the forest near the capital city, having ventured into it many times before as part of the Princess\'s personal guard. Her eccentric habits are some comfort now for how they\'ve prepared you, as otherwise you\'d be unfamiliar with the forest paths. You weren\'t born in this city, after all, or any of the villages on its outskirts.\n
As you travel, careful that none follow and none lurk in the shadows falling deep across the path and the forest to either side, you make good progress through the forest. Getting to the shore will be a matter of not quite a third of the night\'s passing, leaving you with ample time to make the return journey. Your end destination is at the shore of the Sea of Tears. Is it for the saltiness of the water, you wonder, but cannot decide. All waters of the seas across the moon are salty as far as you know. You\'ve only ever seen the one.\n
You come to a fork in the path, pausing and moving into the deeper shadows to the side to consider your choices. To the right is the most traveled path, one which may have travelers camped alongside it, or have those stragglers trickling into the city venturing its length to arrive before the next day dawns. You\'ve been lucky so far to run across none of those souls, but that luck isn\'t guaranteed to hold.\n
To the left is the shortest route, but also the most dangerous. Veering into a deeper part of the forest, you\'ll have to rely on your clan\'s gifts to handle the rough roads. Your tunic covering your chainmail means you move quietly and don\'t catch the light, but it also makes you a better target to the predators of the woods. While you have ever confidence in your abilities, if you end up wasting time fighting, or worse, become injured, you have no idea how it might affect your mission.\n
Straight ahead is the longest path, one you recall as being more scenic than practical. While it meanders, it\'s unlikely to be traveled at this time of night, both being inconvenient for most villages near the sea or on the far side of the forest, and being less practical than the route to the right.\n
Considering what you know about these routes, which one will you take?', now(), now()),
(8, 'The right path is your best bet, and so you set down it, moving swiftly. For the first half, you come across no other travelers, keeping a steady pace as the stars slowly spin overhead. The scroll is a constant weight on your mind, concealed in a bamboo carrying case slung across your back and underneath your dark tunic.\n
You round a curve in the path, slowing s a flicker of light in the middle distance catches your eyes. Could it be a campfire? If so, then there\'s someone ahead of you, and possibly more on the road. Cautious but feeling the urgency of your mission, what will you do?', now(), now()),
(9, 'While the left path might be most dangerous, it\'s also the fastest. Steeling yourself, you turn down it, moving more slowly than on the better established path. The path grows thin as you move along, all but overgrown by trees and bushes, one section wiped out by a landslide from this last autumn\'s storms. \n
You manage to scramble over the shree, sending a few stones and dirt slides skittering down the mountainside as you go. When you make it across, you\'re about to head off again when a few small stones come skittering down right in front of you.', now(), now()),
(10, 'The central path meanders through meadows and over the smaller brooks and creeks that wind through the forest, but it\'s fairly level, and you trust your speed. Hitting stride, you run along on quiet feet, focussing on the path ahead.\n
As you run, all but flying over the path, you catch sight of a fallen tree cutting across the path in a thickly forested area. You know you could either squirm your way past or climb up the boulders to the left of the path to circumvent the fallen tree, but you might be able to jump and clear the tree as well. It\'s a split second decision to make, but with time not on your side, and you already on the slowest path, what will you do?', now(), now()),
(11, 'You\'re moving quickly, and any camping party shouldn\'t be concerned with individuals traveling down the path at night. Any bandits wouldn\'t be so obvious, and messengers might run down any path at the whim of a noble or royalty at any hour of the day or night.\n
The campfire grows closer, its flickering light dancing between the trees as you run onward. The shape of a wagon emerges under the starlight, along with darker shadows of what must be the camping party members on watch. You\'re almost even with the campfire itself with no alarm raised, and you breathe out in relief, turning your head to look further down the path.\n
Your breath of relief came too soon. A twang catches your ears as the bite of steel through your leg, the pain that flares sharply after more vivid than the ground you hit as you fall. In the chaos that follows, you\'re temporarily tackled and questioned by an overenthusiastic camp sentry. When it comes to light that you\'re a guard, and not only that, a royal guard, as demonstrated by the seal on your sword, the camp is full of apologies, working to treat your injury with limited supplies and some skill. You\'re even lent one of the deer that pulls their wagon to continue on your way.\n
The delay has still cost you, and when you reach the Star Viewing Tower at the seashore, you find no one there. Only a golden scale resting on the table inside the Star Viewing Tower\'s entrance, painted with a smear of dark, dried blood.\n
You collect the scale and return to the Princess, tired and with renewed bleeding from your leg. The Princess is silent as she receives the scale, her expression impossible to read when she sends you away. Without the Pearl of the Seas, the ceremony the following night is considered inauspicious, dooming the whole of the kingdom to uncertain luck for the following year.\n
While you\'re never directly blamed for this, you carry the weight of your failure for the remainder of your service in the Princess\'s personal guard, and resign before the next year\'s ceremony.', now(), now()),
(12, 'You move with caution, listening for the camping party as you slip between the shadows off to the side of the path. As you come closer, you catch sight of the camp sentry, a youth sitting up in the branches of a tree overlooking the area. They\'re well disguised, but with your training, spotting them while moving so carefully is well within your capabilities.\n
Taking extra care to not attract unnecessary attention, you slowly pass by the camp and its sentry, only returning to the path after you\'ve ensured no one else is visible coming or going. Two more times along the way you step off the path and slip through the underbrush on feet as light as you can make them, arriving at the Star Viewing Tower with just enough time to spare.\n
The caution from earlier has you approaching the Star Viewing Tower with care, which is how you see the golden dragon coiled up and resting in its deeper shadows. As you hide within the dark treeline yourself, you look between the dragon and the tower door.', now(), now()),
(13, 'You look up the slope of the mountain, trying to determine what the stones were disturbed in the first place. Is there any further instability? \n
Your eyes rest on a canine shape upslope, ears perked forward, head cocked to the side. You\'ve heard of there being Yama Dogs seen in the mountains near the capital, but you hadn\'t expected to come across one in the forest just outside the capital itself. Holding still, you watch for any sign of its intentions. The two of you engage in a staring contest for a matter of minutes. Eventually, the Yama Dog sits down, nodding its head to you, then scratches behind an ear with their hind leg.\n
You bow your head to the Yama Dog in turn, grateful the creature doesn\'t wish to fight tonight. After the exchange of greetings, you calmly walk away, not picking up your pace until you\'re sufficiently far from where you\'d seen the Yama Dog. You don\'t want to accidentally stir up its instinct to chase and kill after having parted ways so peacefully.\n
You reach the Star Viewing Tower with plenty of time to spare, having an otherwise uneventful travel along the dangerous path. Winded, but pleased with yourself, you\'re about to approach the tower itself when you catch sight of movement to its side, in the deeper shadows. You pause, assessing the situation, and approach with care. You see a great dragon coiled around itself, appearing a soft gold in the starlight.', now(), now()),
(14, 'With the small stones bouncing down the slope, you\'re concerned that the mountainside\'s instability may lead to another slide. You can\'t afford to be taken out by one even on a good night, and tonight is certainly not a good night.\n
As you set off at a run, you hear more and more stones sliding and shifting behind you. You\'re picking up speed to get off this portion of the trail before a landslide truly does take you out when a deep, threatening growl reaches your ears. Reaching for your short sword strapped to your side, you have it out of your sheath just as the source of the growling leaps from higher up the mountainside.\n
You twist to the side and manage to deflect the attacker, seeing little more than a blur of black fur and white teeth paired with red eyes. The creature hits the ground and immediately leaps for you again, fangs bared.\n
You recognise your opponent as a Yama Dog, one of the creatures you wouldn\'t expect to find this near the capital. They\'re fierce fighters, fast and temperamental, and while you manage to deflect many of its attacks, you find it difficult to land more than superficial hits on the beast. Your own chainmail protects your core and upper arms, but early in the fight, the Yama Dog scores a hit with their teeth on the skin of your forearm. Fighting while blood makes your sword grip increasingly slippery, you switch hands, eventually managing to maneuver yourself into a superior position. When you knock the Yama Dog back, you turn and leap for the lower branches of a sturdy crystal tree, hauling yourself upward just ahead of the Yama Dog\'s snapping jaws.\n
The Yama Dog remains at the base of the tree, pacing back and forth with intermittent growls, looking up at you and pausing every so often to evaluate the trunk of the tree. While the Yama Dog doesn\'t manage to climb, it does seem content to wait you out for the night.\n
You take the opportunity to bind the wound to your arm and clean your sword hilt. With those tasks handled, you move to a lower branch, baiting the Yama Dog into occasionally leaping up at you, jaws snapping at the air. When you have a sense for the Yama Dog\'s movements, you time a jump down onto its back, driving your sword pommel into its skull. The Yama Dog is knocked unconscious, falling to the ground, and after collecting yourself, you set back off at a run.\n
Unfortunately, by the time you reach the Star Viewing Tower, there\'s no sign of anyone in wait. Grasses to the side of the tower are pressed flat, as if they\'ve born a great weight for some period of time, but nothing remains. Upon entering the tower, you find it empty, the only oddity a golden scale marred by dried blood left sitting on the table right inside the entrance.\n
With a heavy heart, you head back to the city and palace with the scale tucked into your belt pouch. Avoiding the shortest path for fear of encountering the Yama Dog again, you still return before the dawn to be received by the Princess. She listens to your report without more than a word or two, accepting the golden scale with a complicated gaze. She bids you to attend to your wounds, then dismisses you from her presence.\n
Without the Pearl of the Seas, the ceremony that night is considered inauspicious, dooming the whole of the kingdom to uncertain luck for the following year. While you\'re never directly blamed for this, you carry the weight of your failure for the remainder of your service in the Princess\'s personal guard, and resign in the months that follow, returning home to help your parents with their beekeeping.', now(), now()),
(15, 'You run directly for the fallen tree, gathering yourself for a mighty leap. You aim yourself for a gap in the branches, pushing off the ground and flying through the air. You clear the tree, brushing one of the branches as you pass, arms up and out to your sides. As you come back down to the ground, preparing for a landing, you see too late that the path itself has been washed out and left with a dry, jagged creek-bed instead of the raised, compact soil of the path.\n
At the last moment, you tuck yourself into a roll, hitting the ground. A jolt of pain blazes through your shoulder and collarbone, but you keep yourself from breaking an ankle. Wiped out by the unexpected roll, you lay on the ground breathing through the pain and gathering your reserves before you sit up. You\'re a little dizzy, and every shift of your shoulder sends a spike of pain through your chest, but you don\'t appear to be bleeding.\n
Your hip is bruised from where your short sword\'s hilt jammed into it during the unplanned roll, leaving you limping at first once you regain your feet and start walking. You try to pick up your pace, but anytime you start jogging, the jolt of pain through your shoulder and broken collarbone is enough to have your vision start blacking out. Gritting your teeth, you settle into the fastest walk you can manage, only pausing to pull your sash off and construct a sling to support your arm. Once you have the sling, you manage to pick up speed to a ground eating trot, still slower than the pace you\'d set earlier in the night.\n
When you arrive at the Star Viewing Tower, you catch a glimpse of a serpentine form out over the waters of the Sea of Tears, glinting as their scales catch the starlight. Was that a dragon? Why would one be flying over the sea at this time of the night? You have no answer, and more pressing concerns than wondering over the oddities of creatures as powerful as dragons.\n
Examining the tower provides you with evidence of no individual\'s presence. To one side of the tower, in its deeper shadows, you find the grasses tamped down, as if a great weight had been resting on them recently. A few prints of human-sized feet are in the softer soil near the door, but there\'s no evidence of any person inside the tower itself. In fact, the only oddity you can find is a single golden scale left on the table inside the tower\'s entrance, stained with a smear of what might be blood, or dirt, or some other unidentified substance.\n
Heart sinking, you collect the scale into your belt pouch and start back toward the city. By the time you make it back to the palace, it\'s closer to dawn, and the sleepless Princess receives you immediately in the same room as before. She seems aware of your failure as soon as you appear, but she listens to your report, saying very few words. After accepting the scale you found at the Star Viewing Tower, she quietly dismisses you, pausing to add that you should stop by the palace doctors to have your shoulder examined.\n
Without the Pearl of the Seas, the ceremony that night is considered inauspicious, dooming the whole of the kingdom to uncertain luck for the following year. While you\'re never directly blamed for this, you carry the weight of your failure each day after. One evening, you notice a new pendant hanging from the Princess\'s waistband, a single golden scale set into a silver framework of wire and dangling from a golden string. Your heart is filled with grief at this reminder, and you submit your resignation in the days following, returning to the village of your birth and taking over the burdens of your parent\'s deer training stables.', now(), now()),
(16, 'While you\'re certain you could make the jump over the tree, your sense of caution has you deciding to climb the boulders to the left of the path. As you scale upward, nothing seems out of place beyond the fallen tree. As you start climbing down the boulders on the other side, you see what the shadows had hidden on the far side of the fallen tree. Where the path has otherwise been compacted, raised soil, here it\'s been washed out and left as a jagged, dry creekbed. Had you leapt over the fallen tree, you wouldn\'t have avoided crashing into that creekbed, and likely injuring yourself in the process.\n
Glad for avoiding that fate, once you\'re on the path, you roll your shoulders and then set off again, picking up your pace until you\'re loping along once more. No further fallen trees appear, and the few creeks you encounter which aren\'t dry are quickly and easily navigated as the winding path slowly turns toward your destination at the shore of the Sea of Tears.\n
You come out of the forest south of where the Star Viewing Tower is located, making your way up the coast at a more cautious pace. There\'s someone here to be found, after all, though who remains a mystery. As you see the tower emerge over the trees, you also see a large, coiled shape resting in the shadows at its base. You slow down further still, observing from a distance. Is that a dragon? From the shape of the creature and their sheer size, you can\'t imagine they\'re anything else. You clearly need to go closer, but should your focus be on the dragon or finding the mysterious person you\'re to meet?', now(), now()),
(17, 'The dragon remains motionless for a time, only shifting to lift their enormous head from where it\'d been hidden in their coils to look your direction. When they speak, their voice is so deep it echoes in your bones, their whiskers and mane floating as if the dragon was even now swimming through the seas, or flying through the skies, wind dancing along their scales.\n
"You would deign not to greet this esteemed being, is that so?" The sarcasm in the dragon\'s voice is enough to set you on edge, as is the arrogance with which they, or he, speaks. "Come. I will tolerate none of this disrespect." With a crack, the dragon\'s tail swishes out from his coiled form, slamming against the ground. A gust of wind goes flying toward you, sending grit into your eyes and mouth. You unobtrusively spit some sand out of your mouth, blinking through the tears dust has brought to your eyes.', now(), now()),
(18, 'Greeting the dragon, you step forward under the starlight.\n
"Great Dragon, I am the knight called {{name}}. I\'m here on business for my master. Would your esteemed self deign to inform me if any person has come by this tower tonight?"\n
The dragon lifts their head from their coils, studying you with intense gold eyes. Their whiskers and mane shift and flow as if a wind constantly tugs at them, a constant source of movement. Appeased by your greeting, the dragon lifts their head higher, slowly uncoiling. First one great taloned foot, then another, comes to rest on the ground before them, their body as a whole slowly unfurling to its full length.\n
"You are the Princess\'s knight," the dragon says, his voice so deep that it all but echoes in your bones. With that sentence, you\'re both surprised and in awe: dragons are creatures that don\'t often choose to interact with the mundane world of the Moon People. Having one not only choose to do so, but to recall the names of those who are not dragons themselves is even more rare.\n
"Yes," you say, coming to a further conclusion as you stand before the great dragon. This dragon is the one you\'re supposed to meet. Why would such a great beast steal the Pearl? These thoughts quiet as they step out of the deeper shadows, the starlight highlighting the softened gold of their scales. "She\'s tasked me with giving you a gift in exchange for the return of the Pearl of the Seas."\n
The dragon has come closer, looming overhead and staring down at you. He lowers his head until his eyes are level with yours. You have to choose just one eye to look into. His face is simply too big for you to look into both eyes at once.\n
"Has she." \n
Unnerved but unwilling to show it, you bow your head, moving to grasp the bamboo carrying case strapped across your back, underneath your tunic. When you\'ve brought it over your shoulder and have extracted it from your tunic, you open the carrying case, carefully extracting the scroll. The dragon watches your every movement.\n
"Unroll the scroll." He waits, and you hesitate before following his command, carefully unrolling the scroll and holding it up so that the great dragon can read it. His large, golden eyes stare intently at the scroll for what feels like hours, but could be no more than seconds. When he closes his eyes, you breathe out in a sigh of relief without thinking.\n
"I see… if this is the case, then here." He opens his eyes again, lifting a front foot, revealing a fist-sized pearl clutched in the curve of a single talon. "Consider the gift received."\n
Intimidating as it is to reach toward those talons as long as your arm, you roll the scroll again and step forward to gently free the pearl from where it rests in the curve of the dragon\'s talon. As you step back, the pearl now in your hands, you\'re flooded with a sense of awe and relief so intense you almost collapse to your knees.\n
"Great Dragon, this lowly knight thanks you for your upstanding, honourable ways!" Given you\'re speaking to a thieving dragon, it may be over the top, but insulting him seems like a bad idea. You bow to the dragon, hoping to start back toward the city. You still need to return before the dawn breaks over the horizon.\n
The dragon doesn\'t respond at first, simply observing you as you hold your bow. He brings his foot back down, talons digging gently into the grasses and dirt you both stand on.\n
"Your task is complete, knight. You may go. Or," the dragon says, the intensity of his stare on you like an oppressive weight, "You may do me a favour in turn."', now(), now()),
(19, 'You approach the dragon on his request, saying not a word. The dragon stares down at you, eyes narrowed with his disapproval. His tail slams against the ground again, wind gusting around you both.\n
"Introduce yourself, knight, before this one loses his patience with your ineffectiveness!"', now(), now()),
(20, 'You politely decline, stating your need to return to the city and palace for the Princess\'s sake means you must move swiftly. The dragon regards you for a long moment, then turns away, head lowering a few degrees. While you don\'t understand why, you know where your priorities lay. Taking the dragon\'s turning away to be permission, you head back toward the nearest path, picking up your pace until you\'re racing along toward the city, mindful of the obstacles you may encounter along the way.\n
The Pearl of the Seas is carried in a pouch hung around your neck, one that keeps its inner light and magic hidden from all eyes and magical senses. Once you\'ve quietly entered the palace again, you make your way to the same room you\'d met the Princess in earlier in the evening. Dawn is not far off, and the pearl weighs heavy around your neck. \n
The Princess is already waiting, turning toward you as you enter the room. She\'s standing below the same tapestry as earlier, the serpentine dragon flying over stormy seas feeling far too relevant tonight.\n
"You\'ve done it," she says, her eyes falling to where the Pearl of the Seas hangs from around your neck. You lift the cord of the pouch over your head, tugging it through the top of your tunic to offer the whole of it to the Princess. She takes it gracefully into her hands, her features softening as she opens the pouch and touches the peerless pearl found within.\n
"Thank you, Knight {{name}}," she says, still looking at the pearl. When her eye lift, briefly finding yours, emotions you dare not name seem to be in turmoil there. You look away as she continues speaking. "Was there anything that person said to you, after you showed them the scroll?"\n
You pause, remembering over what the dragon had done, then faithfully repeat all that happened, best that you recall. She listens quietly, making no other sound until you\'ve finished. Then, with an "I see," she pulls the pouch holding the pearl closed, tucking it into her sleeve. Soon after, she dismisses you, thanking you again for your great service to your nation and your Princess in recovering the Pearl of the Seas.\n
With the Pearl of the Seas safely in her hands, the ceremony later that day goes as planned, her dance even more beautiful than in past years. Some of those watching in the crowd said it almost broke their hearts, her goodbye to the passing year was so poignant. You agree, but it doesn\'t quite feel right to say it\'s the year that\'s gone… but it\'s not your job to speculate on what or to whom else the Princess might be bidding farewell.\n
You remain in Princess Kaguya\'s personal guard for the rest of your career, and while the Princess never marries or takes a consort, she\'s hardly the first to do so, and never the last. ', now(), now()),
(21, 'The dragon stares down at you, unblinking and unmoving. Feeling increasingly nervous, both by the dragon\'s behaviour and the looming deadline for you getting the Pearl of the Seas back to the Princess, you swallow and speak again.', now(), now()),
(22, 'Swallowing, you raise your head. "This knight would be honoured to hear of any request they may be able to assist the Great Dragon with, as long as it doesn\'t interfere with my delivery of the Pearl of the Seas to my master."\n
The dragon, content with this answer, lifts his head once more.\n
"Truly, one good knight is worth their weight in gold." Rearing up, for a moment, he seems poised to strike you down, but instead, his talons are turned toward the scales on his chest. With care, he pinches a large scale between two talons, pulling it free with a flash of heat and light. Droplets of blood are visible on the surrounding scales, as well as the one he now holds out to you. \n
"Deliver this to the Princess. Inform her that if she accepts, there will be no time for regrets."\n
Strangely, the blood on the scale itself is pooling in its center, forming a dark bead that might be red under better light. You tuck the Pearl of the Seas into a pouch around your neck designed for carrying magical objects, capable of cutting off its soft glow and dimming its magical energy so that it\'s not detectable to those sensitive to such things. Then with equal care, you accept the scale from the dragon, wondering if it\'s truly the dragon\'s heart scale. Such a thing is unimaginable if so. Won\'t a dragon die without their heart scale? In accepting this, would the Princess be dooming a dragon to death?\n
Unable to follow the logic behind the dragon\'s request, nonetheless, as you\'ve said you\'ll do as he asks, there\'s nothing to say aside from, "This knight understands." Wrapping the scale and its strange bead of blood in a bit of waxed cloth in your belt pouch, you bow again to the dragon, bidding him farewell. In your heart, you wonder if this will be the great dragon\'s last night with the living, sadness at such a loss washing through you.\n
You take care as you race back to the city not to take unnecessary risks. With your doubly precious burdens, you can\'t chance or leave anything to fate. Or you\'re leaving everything to fate. Who\'s to say? You\'re certainly no philosopher or theologian. All you know is your relief once you slip back inside the palace after greeting the guards you know at the entrance, your absence nothing more than a knight running errands for their master as far as they know. They\'re not exactly wrong, if mistaken in the scope of your activities.\n
The Princess is already waiting, turning toward you as you enter the room. She\'s standing below the same tapestry as earlier, the serpentine dragon flying over stormy seas feeling far too relevant tonight.\n
"You\'ve done it," she says, her eyes falling to where the Pearl of the Seas hangs from around your neck. You lift the cord of the pouch over your head, tugging it through the top of your tunic to offer the whole of it to the Princess. She takes it gracefully into her hands, her features softening as she opens the pouch and touches the peerless pearl found within.\n
"Thank you, Knight {{name}}," she says, still looking at the pearl. When her eye lift, briefly finding yours, emotions you dare not name seem to be in turmoil there. You look away as she continues speaking. "Was there anything that person said to you, after you showed them the scroll?"\n
You pause, remembering over what the dragon had done, then faithfully repeat all that happened, best that you recall. She listens quietly, making no other sound until you\'ve finished and presented her with the scale. In the light of the room, the gold all but burns with its own light. The strange bead of blood remains in the center of the scale, a deep, rich crimson.\n
"The Great Dragon said that if you accept, Princess, there won\'t be time for regrets." Finding it an ominous statement even now, your concern is apparently evident to the Princess. She glances up at you, her smile small but reassuring. For once, it even seems to reach her dark eyes.\n
"Yes, I imagine that would be true. Thank you, Knight {{name}}. Truly, one good knight is priceless in this world or any other."\n
It\'s so startlingly similar to what the dragon had said that you blink, caught by surprise. Not long after, the Princess dismisses you, and the exhaustion of your day and night have you heading for your bed in the room shared with two of your fellow knights in the Princess\'s personal guard. You\'re asleep almost before your head touches your pillow. Your last thought is a passing sorrow for the potential loss of a great dragon in this world, and then your thoughts are nothing but dreams and darkness.\n
With the Pearl of the Seas safely in Princess Kaguya\'s hands, the ceremony later that day goes as planned, her dance even more beautiful than in past years. Some of those watching in the crowd said it almost broke their hearts, her welcome for the new year was so poignant. You agree, even as you wonder about that scale, and what accepting or declining the Princess had done after you\'d left her in the early hours of the morning. You\'ll never ask, as it isn\'t your place, but you\'re free to wonder all you like.\n
Soon enough, the regular cadence of life and your duties has such thoughts buried under more immediate concerns. It\'s not until the surprise announcement some half year late of the Princess\'s engagement and the arrival in the months after of her Prince Consort that you start wondering again about that great dragon. \n
Even then, you\'re not sure why, not until the day you first see the Prince Consort. He doesn\'t greet any of the knights who guard the Princess\'s chambers, or accompany her as she moves around the palace and city, a perfectly reserved and untouchable member of the nobility. It\'s only when you see his eyes, a deep and striking gold, that you remember a night many months earlier, and an improbably large head moving to be eye level with you.\n
The Prince Consort\'s gaze doesn\'t linger on you, nor yours on his, as is only appropriate. Yet when he passes by, he lingers for half a moment, saying in words that only reach your ears:\n
"Truly, one good knight is worth their weight in gold." He\'s gone before you can think to respond, and in your heart, you\'re gladdened to think that perhaps the sacrifice made had not cost what you suspected. Perhaps accepting one thief was accepting the willing theft of another.\n
You remain in the Princess\'s personal guard for the rest of your career, part of the honour guard at her wedding to her Prince Consort, Mikado. You consider it a blessing that you\'re able to witness their quiet and strong love over the years, touched at how the Princess Kaguya, never cruel, turns from a perfunctorily pleasant woman into a noble princess of genuine warmth to match her political savvy. When you finally retire, it\'s with the blessing of both the Princess Kaguya and Prince Consort Mikado, along with an almost ridiculous stipend: your weight in gold.\n
After all, while the Princess believed one good knight was priceless, the Prince Consort reasoned one good knight still had to support their weight, in gold or otherwise.', now(), now());

INSERT INTO choice (description, storyID, orderID,  routeID, createdAt, updatedAt) VALUES 
('> You ask what Princess Kaguya needs saving from.', 1, 1, 2, now(), now()),
('> You immediately accept the mission without further question.', 1, 2, 3, now(), now()),
('> You stare blankly, tired and caught by surprise.', 1, 3, 4, now(), now());